### ISSUE TITLE
Not able to resolve container host name

### ISSUE THREAD

**Issue by myatmin** [serjs/socks5-server#30]
Is it possible to resolve container host name?

```
services:
   proxy-socks5:
    container_name: proxy-socks5
    image: serjs/go-socks5-proxy:latest
    ports:
      - 1080:1080
  db:
    container_name: db-something
    image: ...
```

Able to `curl --socks5 127.0.0.1:1080 <container ip and port>`
Not able to `curl --socks5 127.0.0.1:1080 <container host name and port>`

Environment:
Docker version 20.10.14 on Windows with WSL2 enabled
