### ISSUE TITLE
security: can access other containers' private ports by default

### ISSUE THREAD

**Issue by WofWca** [serjs/socks5-server#72]
The default setup (no `ALLOWED_DEST_FQDN` used`) allows the SOCKS proxy client to access private addresses of the machine on which the SOCKS server is running on. In particular, it can access the services running on other Docker containers with the default network (bridge).

PoC:
1. `docker run -d --name socks5 -p 1080:1080 serjs/go-socks5-proxy`.
2. `docker run --rm --name web-test crccheck/hello-world` to launch a server. Note that we don't use `-p` to publish a port!
3. `docker network inspect bridge | grep "hello-world-server" -A 5` to find the IP of the HTTP server.
4. Now, use another machine to connect to the SOCKS server. Run
    
    ```bash
    curl --proxy "socks5://localhost:2080" http://172.42.0.3:8000
    ```
    
    Replace `172.42.0.3` with the IP address from step 3.

You got the response! But perhaps you shouldn't have. I say only public IPs should be accessible by default, especially given that this project seems to be noob-oriented. At least we should have a warning in the README.

**Comment by bobpaul** [comment]
See `docker network` or look into [Docker Compose](https://docs.docker.com/compose/) to set up your containers with more segregation. 

A simple setup I have looks like:

```
service:
    traefik:
        networks:
            public:
        ports:
            - 80:80
            - 443:443
    nextcloud:
        networks:
            public:
            nextcloud-db
    mariadb:
        networks:
            nextcloud-db
    vpn:
       networks:
            vpn-net:
        ports:
            - 127.0.0.1:9080:1080
    proxy:
        image: serjs/go-socks5-proxy
        network_mode: "service:vpn"
        depends_on:
            vpn:
                condition: service_healthy
```

To understand this example: traefik is a reverse proxy (nginx and apache2 can do this role, too). When traefik sees an http request for `https://nextcloud.example.com` it's redirected to my nextcloud container on the `public` network. Mariadb can't even talk to the internet as I have the `nextcloud-db` network configured as internal. Traefik can't talk to mariadb because the traefik container is not on the `nextcloud-db` network. There's no need to teach mariadb or nextcloud to ignore requests from other containers since other containers can't talk to them.

Likewise the vpn container is on `vpn-net` and is unable to talk to mariadb or nextcloud. Because of the `network_mode` setting, the proxy container doesn't have its own IP; it shares the same network stack as the vpn container (and that's why the proxy ports are defined in the in the `vpn` service's definition even though they're meant for the proxy). On the host computer, I can use `127.0.0.1:9080` as my socks proxy to use the VPN. Any of my containers that need VPN can join the `vpn-net` network and use `vpn.vpn-net:1080` as the proxy (again, the proxy container doesn't have its own network, so other containers need to use the vpn container's address)

The default docker bridge (the one used if you `docker run container/name` without specifying the `--network` option is something I _never_ use for anything other than brief testing.

I would also recommend adjusting your `daemon.json` to [reduce the subnetsize of docker networks](https://old.reddit.com/r/selfhosted/comments/1az6mqa/psa_adjust_your_docker_defaultaddresspool_size/) down to `/24`. Docker's default configuration is very wasteful in the `172.16.0.0/12` address space and if you leave the default settings, you only get a handful of networks before docker starts consuming `192.168.0.0/16` and `10.0.0.0/8` address space.
